begin;
select plan(20);
select has_table('trip_private','email_hmac_keys','purpose/environment/version HMAC keys exist');
select has_function('trip_private','produce_offline_grant_receipt',array['uuid','uuid','text','text','bigint','jsonb','timestamp with time zone'],'offline signer producer command exists');
select has_function('trip_private','produce_invitation_receipt',array['uuid','text','bytea','text','timestamp with time zone','text'],'invitation signer producer command exists');
select has_function('app_public','set_trip_start',array['text','text','text','double precision','double precision','integer'],'start/departure command exists');
select has_function('app_public','set_trip_return',array['text','boolean','text','double precision','double precision'],'return command exists');
select has_function('app_public','set_trip_limits',array['text','double precision','integer'],'limits command exists');
select has_function('app_public','add_rest_stop',array['text','text','text','text','integer','double precision','double precision'],'rest stop command exists');
select has_function('app_public','mark_trip_stop_closed',array['text','text'],'observed closed command exists');
select has_function('app_public','restore_trip_stop',array['text','text'],'restore stop command exists');
select has_function('app_public','complete_trip',array['text'],'complete trip command exists');
select has_function('app_public','save_trip_visit_memory',array['text','text','integer','text','text'],'visit memory command exists');
select ok((select pg_get_functiondef(p.oid) like '%departure_local_time is not null%' and pg_get_functiondef(p.oid) like '%navigator_device_hash%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app_public' and p.proname='start_trip'),'start requires departure, valid start, Navigator, and device');
select ok((select pg_get_functiondef(p.oid) like '%location_purged_at=statement_timestamp()%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app_public' and p.proname='complete_trip'),'completion purges precise trip locations');
select ok((select pg_get_functiondef(p.oid) like '%extensions.hmac%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='trip_private' and p.proname='email_hmac'),'email binding uses HMAC rather than a plain digest');
select ok(not has_table_privilege('authenticated','trip_private.email_hmac_keys','SELECT'),'browser cannot read HMAC keys');
select ok(not has_function_privilege('authenticated','trip_private.produce_offline_grant_receipt(uuid,uuid,text,text,bigint,jsonb,timestamptz)','EXECUTE'),'browser cannot produce offline grants');
select ok(not has_function_privilege('authenticated','trip_private.produce_invitation_receipt(uuid,text,bytea,text,timestamptz,text)','EXECUTE'),'browser cannot produce invitation receipts');
select ok((select not rolcanlogin and not rolsuper and not rolbypassrls from pg_roles where rolname='trip_email_key_manager'),'HMAC key manager is constrained');
set local role anon;
select throws_ok($$select app_public.complete_trip('00000000-0000-0000-0000-000000000000')$$,'42501','anonymous completion denied');
select throws_ok($$select app_public.set_trip_limits('00000000-0000-0000-0000-000000000000',10,60)$$,'42501','anonymous planning mutation denied');
reset role;
select * from finish();rollback;
