begin;
create extension if not exists pgtap with schema extensions;
select plan(41);

select has_table('rg01_private','rg01_command_receipts','RG-01 has durable idempotent command receipts');
select has_table('rg01_private','rg01_lifecycle_receipts','RG-01 has content-free lifecycle observations');
select has_column('rg01_private','rg01_signing_challenges','idempotency_key','decision challenges have an idempotency key');
select has_column('rg01_private','rg01_signing_challenges','request_digest','decision challenge inputs are digest bound');
select ok((select not collection_enabled from rg01_private.rg01_capability where singleton_id=1),'RG-01 collection remains disabled by default');
select ok((select count(*)=2 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='rg01_private' and c.relname in ('rg01_command_receipts','rg01_lifecycle_receipts') and c.relrowsecurity and c.relforcerowsecurity),'new operational tables force RLS');
select ok(not exists(select 1 from information_schema.role_table_grants where table_schema='rg01_private' and table_name in ('rg01_command_receipts','rg01_lifecycle_receipts') and grantee in ('anon','authenticated','service_role')),'browser and generic service roles cannot read operational receipts');
select ok(not exists(select 1 from information_schema.columns where table_schema='rg01_private' and table_name in ('rg01_command_receipts','rg01_lifecycle_receipts') and column_name ~ '(subject|user|trip_content|note|review|support_content|claim_evidence|defect_text|signature)'),'operational receipts contain no prohibited private content');
select ok((select pg_get_constraintdef(oid) ilike '%signature%' from pg_constraint where conrelid='rg01_private.rg01_command_receipts'::regclass and conname='rg01_command_result_content_free'),'command result shape explicitly excludes signatures and private content');
select ok((select count(*)=2 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='rg01_private' and c.relname in ('rg01_command_receipts','rg01_lifecycle_receipts') and not t.tgisinternal and pg_get_triggerdef(t.oid) ilike '%deny_mutation%'),'operational receipts are append-only');

select has_function('app_public','rg01_get_operational_status',array['uuid'],'Product Owner status RPC exists');
select has_function('app_public','rg01_execute_calculation',array['text','jsonb'],'calculation command RPC exists');
select has_function('app_public','rg01_request_decision_challenge',array['uuid','text','uuid'],'idempotent Product Owner challenge RPC exists');
select has_function('app_public','rg01_consume_verified_decision',array['uuid','bytea','bytea','text','text','uuid'],'verified consume RPC exists');
select has_function('app_public','rg01_complete_verified_purge',array['uuid','text','bytea','text','uuid'],'verified purge RPC exists');
select has_function('app_public','rg01_lifecycle_watchdog',array['timestamp with time zone'],'lifecycle watchdog RPC exists');
select ok(has_function_privilege('authenticated','app_public.rg01_get_operational_status(uuid)','EXECUTE') and not has_function_privilege('anon','app_public.rg01_get_operational_status(uuid)','EXECUTE'),'status is authenticated only');
select ok(has_function_privilege('rg01_calculation_service','app_public.rg01_execute_calculation(text,jsonb)','EXECUTE') and not has_function_privilege('authenticated','app_public.rg01_execute_calculation(text,jsonb)','EXECUTE'),'only calculation service begins and freezes');
select ok(has_function_privilege('authenticated','app_public.rg01_request_decision_challenge(uuid,text,uuid)','EXECUTE') and not has_function_privilege('authenticated','app_public.rg01_request_decision_challenge(uuid,text)','EXECUTE'),'only the idempotent challenge surface remains available');
select ok(has_function_privilege('rg01_signature_service','app_public.rg01_consume_verified_decision(uuid,bytea,bytea,text,text,uuid)','EXECUTE') and not has_function_privilege('authenticated','app_public.rg01_consume_verified_decision(uuid,bytea,bytea,text,text,uuid)','EXECUTE'),'browser cannot submit signature evidence');
select ok(has_function_privilege('rg01_lifecycle_service','app_public.rg01_complete_verified_purge(uuid,text,bytea,text,uuid)','EXECUTE') and not has_function_privilege('authenticated','app_public.rg01_complete_verified_purge(uuid,text,bytea,text,uuid)','EXECUTE'),'only lifecycle service completes verified purge');
select ok(has_function_privilege('rg01_lifecycle_service','app_public.rg01_lifecycle_watchdog(timestamp with time zone)','EXECUTE') and not has_function_privilege('authenticated','app_public.rg01_lifecycle_watchdog(timestamp with time zone)','EXECUTE'),'only lifecycle service runs the watchdog');

select ok(position($q$not exists(select 1 from rg01_private.rg01_product_owner_grants$q$ in lower(pg_get_functiondef('app_public.rg01_get_operational_status(uuid)'::regprocedure)))>0,'status requires an active Product Owner grant');
select ok(position('rg01_private.source_head_digest()' in lower(pg_get_functiondef('app_public.rg01_get_operational_status(uuid)'::regprocedure)))>0,'status reports binding to the current live source head');
select ok(position($q$array['runid','idempotencykey','windowstart','windowend','supersedesreceiptid']$q$ in replace(lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)),' ',''))>0,'begin uses an exact operational allowlist');
select ok(position($q$array['runid','idempotencykey']$q$ in replace(lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)),' ',''))>0,'freeze accepts only run and idempotency IDs');
select ok(position($q$array['totals','denominator','exclusions','signature','failedcodes']$q$ in replace(lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)),' ',''))>0,'calculation rejects browser totals exclusions and signatures');
select ok(position('rg01_private.begin_run' in lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)))>0 and position('rg01_private.freeze_run' in lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)))>0,'commands delegate to durable authoritative calculation functions');
select ok(position('rg01_idempotency_key_reused' in lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)))>0 and position('rg01_command_receipts' in lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)))>0,'calculation replays exact results and rejects key reuse');
select ok(position($q$p_window_end-p_window_start>'180days'::interval$q$ in regexp_replace(lower(pg_get_functiondef('rg01_private.begin_run(uuid,timestamp with time zone,timestamp with time zone,uuid)'::regprocedure)),'[[:space:]]','','g'))>0,'authoritative begin enforces the maximum 180-day window');
select ok(position('count(*)intofirst_count,second_count,trip_countfromq;' in regexp_replace(lower(pg_get_functiondef('rg01_private.freeze_run_derived_core(uuid)'::regprocedure)),'[[:space:]]','','g'))>0,'all qualifying trips remain in the support denominator');
select ok(position('rg01_exclusions' in lower(pg_get_functiondef('rg01_private.freeze_run_derived_core(uuid)'::regprocedure)))>0 and position('rg01_subject_consents' in lower(pg_get_functiondef('rg01_private.freeze_run_derived_core(uuid)'::regprocedure)))>0,'freeze derives exclusions from authoritative subject records');

select ok(position('current_session_has_mfa()' in lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)))>0 and position($q$current_session_recent_auth(interval '15 minutes')$q$ in lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)))>0,'Product Owner challenge requires MFA and recent authentication');
select ok(position('r.source_head_digest<>rg01_private.source_head_digest()' in replace(lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)),' ',''))>0,'a stale live-source binding blocks signing');
select ok(position($q$p_decision='pass'andcardinality(r.blockers)>0$q$ in replace(lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)),' ',''))>0,'failed predicates block PASS');
select ok(position('rg01_idempotency_key_reused' in lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)))>0 and position('consumed_at' in lower(pg_get_functiondef('app_public.rg01_request_decision_challenge(uuid,text,uuid)'::regprocedure)))>0,'one-use challenges replay safely');
select ok(position('rg01_private.consume_decision_challenge' in lower(pg_get_functiondef('app_public.rg01_consume_verified_decision(uuid,bytea,bytea,text,text,uuid)'::regprocedure)))>0 and position('rg01_command_receipts' in lower(pg_get_functiondef('app_public.rg01_consume_verified_decision(uuid,bytea,bytea,text,text,uuid)'::regprocedure)))>0,'verified consume is idempotent around the durable signing boundary');
select ok(position('rg01_private.purge_run_linkage' in lower(pg_get_functiondef('app_public.rg01_complete_verified_purge(uuid,text,bytea,text,uuid)'::regprocedure)))>0 and position('p_provider_verification_id' in lower(pg_get_functiondef('app_public.rg01_complete_verified_purge(uuid,text,bytea,text,uuid)'::regprocedure)))>0,'linkage purge requires a verified destruction receipt');
select ok(position($q$'purge_overdue'$q$ in lower(pg_get_functiondef('app_public.rg01_lifecycle_watchdog(timestamp with time zone)'::regprocedure)))>0 and position('rg01_private.purge_run_linkage' in lower(pg_get_functiondef('app_public.rg01_lifecycle_watchdog(timestamp with time zone)'::regprocedure)))=0,'watchdog alerts but never fabricates or performs purge');
select ok(position('rg01_receipt_supersessions' in lower(pg_get_functiondef('rg01_private.begin_run(uuid,timestamp with time zone,timestamp with time zone,uuid)'::regprocedure)))>0 and position('rg01_prior_linkage_purge_required' in lower(pg_get_functiondef('rg01_private.begin_run(uuid,timestamp with time zone,timestamp with time zone,uuid)'::regprocedure)))>0,'supersession requires current receipt linkage and prior purge');
select ok(position('community_private' in lower(pg_get_functiondef('app_public.rg01_execute_calculation(text,jsonb)'::regprocedure)))=0 and position('community_private' in lower(pg_get_functiondef('app_public.rg01_consume_verified_decision(uuid,bytea,bytea,text,text,uuid)'::regprocedure)))=0,'RG-01 commands never activate or select a community');

select * from finish();
rollback;
