begin;
create extension if not exists pgtap with schema extensions;
select plan(47);

select has_table('review_private','reviewer_verifier_config','reviewer verifier configuration is durable');
select has_table('review_private','reviewer_credentials','reviewer credentials are durable');
select has_table('review_private','reviewer_credential_challenges','reviewer challenges are durable');
select has_table('review_private','reviewer_credential_command_receipts','credential revocation is idempotent');
select is((select state from review_private.reviewer_verifier_config where singleton),'blocked','reviewer verifier defaults blocked');
select is((select count(*) from review_private.reviewer_credentials),0::bigint,'migration fabricates no reviewer credential');
select ok(not exists(select 1 from review_private.reviewer_identities where state='active'),'legacy caller-asserted reviewer activation is invalidated');
select ok((select count(*)=4 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='review_private' and c.relname in ('reviewer_verifier_config','reviewer_credentials','reviewer_credential_challenges','reviewer_credential_command_receipts') and c.relrowsecurity and c.relforcerowsecurity),'all reviewer credential tables force RLS');
select ok(not exists(select 1 from information_schema.role_table_grants where table_schema='review_private' and table_name in ('reviewer_verifier_config','reviewer_credentials','reviewer_credential_challenges','reviewer_credential_command_receipts') and grantee in ('anon','authenticated','service_role')),'browser and generic service roles have no direct credential access');
select ok((select pg_get_constraintdef(oid) ilike '%not discoverable%' from pg_constraint where conrelid='review_private.reviewer_credentials'::regclass and pg_get_constraintdef(oid) ilike '%discoverable%'),'credential records must be non-discoverable');
select ok(exists(select 1 from pg_indexes where schemaname='review_private' and tablename='reviewer_credentials' and indexdef ilike '%unique%credential_id_digest%'),'credential IDs are distinct');
select ok(exists(select 1 from pg_indexes where schemaname='review_private' and tablename='reviewer_credentials' and indexdef ilike '%unique%provider_credential_id%'),'provider credential IDs are distinct');
select ok(exists(select 1 from pg_indexes where schemaname='review_private' and indexname='reviewer_assertion_challenge_once' and indexdef ilike '%unique%'),'each assertion challenge can produce one receipt');
select ok(exists(select 1 from pg_trigger where tgname='reviewer_credentials_guarded_delete' and not tgisinternal),'credential authority deletes only after a keyed reuse marker exists');

select has_function('review_private','reviewer_has_two_active_credentials',array['uuid'],'server credential count predicate exists');
select has_function('review_private','provision_reviewer_identity',array['uuid','bytea'],'pending identity provisioning exists');
select has_function('review_private','configure_reviewer_verifier',array['text','text','text','bytea','bigint'],'verifier evidence configuration exists');
select has_function('review_private','revoke_reviewer_verifier',array['text'],'verifier revocation exists');
select has_function('app_public','reviews_request_reviewer_credential_challenge',array['uuid','uuid','text','uuid'],'fresh challenge RPC exists');
select has_function('review_private','complete_reviewer_registration',array['uuid','bytea','bytea','text','text','text','boolean','bigint'],'verifier registration completion exists');
select has_function('review_private','complete_reviewer_assertion',array['uuid','bytea','bytea','text','text','bigint'],'verifier assertion completion exists');
select has_function('app_public','reviews_complete_reviewer_registration',array['uuid','bytea','bytea','text','text','text','boolean','bigint'],'PostgREST verifier registration boundary exists');
select has_function('app_public','reviews_complete_reviewer_assertion',array['uuid','bytea','bytea','text','text','bigint'],'PostgREST verifier assertion boundary exists');
select has_function('app_public','reviews_revoke_reviewer_credential',array['uuid','uuid'],'reviewer credential revocation exists');
select ok(to_regprocedure('review_private.register_reviewer_identity(uuid,bytea,integer)') is null,'caller-supplied credential-count registration is removed');
select ok(to_regprocedure('review_private.record_reviewer_assertion(uuid,uuid,bytea,bytea,text)') is null,'caller-supplied assertion digests are removed');

select ok(has_function_privilege('review_credential_configurator','review_private.configure_reviewer_verifier(text,text,text,bytea,bigint)','EXECUTE') and not has_function_privilege('authenticated','review_private.configure_reviewer_verifier(text,text,text,bytea,bigint)','EXECUTE'),'only configurator accepts verifier evidence');
select ok(has_function_privilege('review_credential_verifier','review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)','EXECUTE') and not has_function_privilege('authenticated','review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)','EXECUTE'),'only verifier records registration results');
select ok(has_function_privilege('review_credential_verifier','review_private.complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)','EXECUTE') and not has_function_privilege('authenticated','review_private.complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)','EXECUTE'),'only verifier records assertion results');
select ok(has_function_privilege('review_credential_verifier','app_public.reviews_complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)','EXECUTE') and not has_function_privilege('authenticated','app_public.reviews_complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)','EXECUTE'),'browser cannot call verifier registration boundary');
select ok(has_function_privilege('review_credential_verifier','app_public.reviews_complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)','EXECUTE') and not has_function_privilege('authenticated','app_public.reviews_complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)','EXECUTE'),'browser cannot call verifier assertion boundary');
select ok(not has_function_privilege('authenticated','app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)','EXECUTE') and not has_function_privilege('anon','app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)','EXECUTE'),'ordinary account-session challenge RPC is disabled');

select ok(position($q$state='pending'$q$ in replace(lower(pg_get_functiondef('review_private.provision_reviewer_identity(uuid,bytea)'::regprocedure)),' ',''))>0 and position('active_credential_count,assertion_verified_at' in replace(lower(pg_get_functiondef('review_private.provision_reviewer_identity(uuid,bytea)'::regprocedure)),' ',''))>0,'provisioning cannot activate a reviewer');
select ok(position('current_session_has_mfa()' in lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)))>0 and position($q$current_session_recent_auth(interval '10 minutes')$q$ in lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)))>0,'challenge request requires MFA and recent auth');
select ok(position($q$state='accepted'$q$ in replace(lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)),' ',''))>0,'no challenge is issued without accepted verifier evidence');
select ok(position('assigned_reviewer_identity_id=i.reviewer_identity_id' in replace(lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)),' ',''))>0,'assertion challenge is bound to the assigned reviewer and case');
select ok(position($q$interval '5 minutes'$q$ in lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)))>0 and position('challenge_nonce' in lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)))>0,'server creates a fresh five-minute challenge');
select ok(position('reviewer_challenge_idempotency_reused' in lower(pg_get_functiondef('app_public.reviews_request_reviewer_credential_challenge(uuid,uuid,text,uuid)'::regprocedure)))>0,'challenge replay rejects key/input mismatch');
select ok(position('p_discoverable' in lower(pg_get_functiondef('review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)'::regprocedure)))>0 and position('provider_key_id<>cfg.provider_key_id' in replace(lower(pg_get_functiondef('review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)'::regprocedure)),' ',''))>0,'registration enforces non-discoverability and accepted verifier key');
select ok(position('cnt>=2' in replace(lower(pg_get_functiondef('review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)'::regprocedure)),' ',''))>0 and position($q$then'active'else'pending'$q$ in replace(lower(pg_get_functiondef('review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)'::regprocedure)),' ',''))>0,'two durable active credentials are required before activation');
select ok(position('registration_challenge_id=p_challenge_id' in replace(lower(pg_get_functiondef('review_private.complete_reviewer_registration(uuid,bytea,bytea,text,text,text,boolean,bigint)'::regprocedure)),' ',''))>0,'lost registration responses replay the prior durable result');
select ok(position('p_sign_count<=cred.sign_count' in replace(lower(pg_get_functiondef('review_private.complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)'::regprocedure)),' ',''))>0,'assertions require a monotonic authenticator counter');
select ok(position('reviewer_has_two_active_credentials' in lower(pg_get_functiondef('review_private.complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)'::regprocedure)))>0,'assertion verification rechecks two active credentials');
select ok(position('where challenge_id=p_challenge_id' in lower(pg_get_functiondef('review_private.complete_reviewer_assertion(uuid,bytea,bytea,text,text,bigint)'::regprocedure)))>0,'lost assertion responses replay the prior receipt');
select ok(position($q$state='revoked'$q$ in replace(lower(pg_get_functiondef('app_public.reviews_revoke_reviewer_credential(uuid,uuid)'::regprocedure)),' ',''))>0 and position($q$else'disabled'$q$ in replace(lower(pg_get_functiondef('app_public.reviews_revoke_reviewer_credential(uuid,uuid)'::regprocedure)),' ',''))>0,'credential revocation disables under-credentialed reviewers');
select ok(position('reviewer_assertion_receipts set consumed_at' in lower(pg_get_functiondef('app_public.reviews_revoke_reviewer_credential(uuid,uuid)'::regprocedure)))>0,'revocation consumes outstanding assertions');
select ok(position('original_moderator_id=actor' in replace(lower(pg_get_functiondef('app_public.reviews_decide_appeal(uuid,text,text)'::regprocedure)),' ',''))>0 and position('original_moderator_id=actor' in replace(lower(pg_get_functiondef('app_public.reviews_decide_restriction_appeal(uuid,text,text)'::regprocedure)),' ',''))>0,'separate-reviewer appeal behavior remains enforced');

select * from finish();
rollback;
